version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /Users/fabiankanhai/Documents/coding/docker/it-begins/api/node_modules